// Sprites PNG générés (tools/gen_sprites_ai.py). Repli SVG si absent.
export const PNG_SPRITES = new Set([
  "binder",
  "books",
  "box",
  "cabinet",
  "calculator",
  "chair",
  "clipboard",
  "coffee",
  "folder",
  "keyboard",
  "lamp",
  "monitor",
  "mug2",
  "pencils",
  "phone",
  "plant",
  "printer",
  "stapler",
  "watercooler",
]);
